=== Tangxinqi/my-spider/spider-core/src/main/resources/template.response.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--        -->

        <!ELEMENT template-response ((template-text | template-xml | template-object | template-array)*, result-set)>
        <!ELEMENT template-text (template-text | template-xml | template-array | template-object)*>
        <!ATTLIST template-text
                id CDATA #IMPLIED
                t-if CDATA #IMPLIED
                depend-on CDATA #IMPLIED
                type-handler CDATA #IMPLIED
                separator CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                >

        <!ELEMENT template-xml (value*)>
        <!ATTLIST template-xml
                id CDATA #IMPLIED
                t-if CDATA #IMPLIED
                depend-on CDATA #IMPLIED
                type-handler CDATA #IMPLIED
                >
        <!ELEMENT template-object (value*)>
        <!ATTLIST template-object
                id CDATA #IMPLIED
                t-if CDATA #IMPLIED
                depend-on CDATA #IMPLIED
                type CDATA #IMPLIED
                >
        <!ELEMENT template-array (value*)>
        <!ATTLIST template-array
                id CDATA #IMPLIED
                t-if CDATA #IMPLIED
                depend-on CDATA #IMPLIED
                type-handler CDATA #IMPLIED
                separator CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                >
        <!ELEMENT value EMPTY>
        <!ATTLIST value
                id CDATA #REQUIRED
                path CDATA #REQUIRED
                >
        <!ELEMENT result-set (result-key)+>
        <!ATTLIST result-set
                type CDATA #IMPLIED
                >
        <!ELEMENT result-key (#PCDATA)>
        <!ATTLIST result-key
                name CDATA #IMPLIED
                >

=== Tangxinqi/my-spider/spider-boot-starter/src/test/resources/response.array.test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE template-response PUBLIC "TTM" "http://localhost:9528/static/template.response.dtd" >
<template-response>
    <template-array separator="\|" open="(" close=")">
        <value id="value1" path="$[0]"/>
        <value id="value2" path="$[1]"/>
        <value id="value3" path="$[2]"/>
        <value id="value4" path="$[3]"/>
    </template-array>
    <result-set>
        <result-key name="key1">${value1}</result-key>
        <result-key name="key2">${value2}</result-key>
        <result-key name="key3">${value3}</result-key>
        <result-key name="key4">${value4}</result-key>
    </result-set>
</template-response>

=== Tangxinqi/my-spider/spider-boot-starter/src/test/resources/response.xml.test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE template-response PUBLIC "TTM" "http://localhost:9528/static/template.response.dtd" >
<template-response>
    <template-xml>
        <value id="test1" path="xml.test1.test1_test1"/>
        <value id="test2" path="xml.test2"/>
        <value id="test3" path="xml.test3"/>
    </template-xml>
    <result-set>
        <result-key name="test1">${test1}</result-key>
        <result-key name="test2">${test2}</result-key>
        <result-key name="test3">${test3}</result-key>
    </result-set>
</template-response>

=== Tangxinqi/my-spider/spider-boot-starter/src/test/resources/response.bean.test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE template-response PUBLIC "TTM" "http://localhost:9528/static/template.response.dtd" >
<template-response>
    <template-object type="com.meituan.pay.supergw.message.boot.starter.test.TestBean">
        <value id="test1" path="key1"/>
        <value id="test2" path="key2"/>
        <value id="test3" path="key3"/>
        <value id="test4" path="key4"/>
    </template-object>
    <result-set type="com.meituan.pay.supergw.message.boot.starter.test.TestBean">
        <result-key name="key1">${test1}</result-key>
        <result-key name="key2">${test2}</result-key>
        <result-key name="key3">${test3}</result-key>
        <result-key name="key4">${test4}</result-key>
    </result-set>
</template-response>
