=== Tangxinqi/my-spider/spider-core/src/main/resources/template.request.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--        -->

        <!ELEMENT template-request (template-text | template-map | template-json | template-xml | template-object | template-array) >
        <!ELEMENT template-text (#PCDATA | template-text | template-json | template-xml | template-array | foreach)*>
        <!ATTLIST template-text
                id CDATA #IMPLIED
                t-if CDATA #IMPLIED
                ignore (true|false) #IMPLIED
                type-handler CDATA #IMPLIED
                >
        <!ELEMENT template-map (key+)>
        <!ATTLIST template-map
                id CDATA #IMPLIED
                t-if CDATA #IMPLIED
                ignore (true|false) #IMPLIED
                >
        <!ELEMENT template-json (key+)>
        <!ATTLIST template-json
                id CDATA #IMPLIED
                t-if CDATA #IMPLIED
                ignore (true|false) #IMPLIED
                type-handler CDATA #IMPLIED
                >
        <!ELEMENT template-xml (#PCDATA | key | foreach)*>
        <!ATTLIST template-xml
                id CDATA #IMPLIED
                t-if CDATA #IMPLIED
                ignore (true|false) #IMPLIED
                type-handler CDATA #IMPLIED
                >
        <!ELEMENT template-object (key+)>
        <!ATTLIST template-object
                id CDATA #IMPLIED
                t-if CDATA #IMPLIED
                ignore (true|false) #IMPLIED
                type CDATA #REQUIRED
                >
        <!ELEMENT template-array (template-text* | template-map* | template-json* | template-xml* | template-object* | template-array* | key* | foreach)+>
        <!ATTLIST template-array
                id CDATA #IMPLIED
                t-if CDATA #IMPLIED
                depend-on CDATA #IMPLIED
                ignore (true|false) #IMPLIED
                type-handler CDATA #IMPLIED
                separator CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                >
        <!ELEMENT foreach (#PCDATA| template-text | template-map | template-json | template-xml | template-object | template-array)*>
        <!ATTLIST foreach
                collection CDATA #REQUIRED
                t-if CDATA #IMPLIED
                item CDATA #REQUIRED
                >
        <!ELEMENT key (#PCDATA | template-text | template-map | template-json | template-xml | template-object | template-array | key)*>
        <!ATTLIST key
                name CDATA #IMPLIED
                t-if CDATA #IMPLIED
                >

=== Tangxinqi/my-spider/spider-boot-starter/src/test/resources/request.xml.test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE template-request PUBLIC "TTM" "http://localhost:9528/static/template.request.dtd" >
<template-request>
    <template-xml>
        <![CDATA[<?xml version="1.0" encoding="UTF-8" ?>]]>
        <key name="xml">
            <key name="test1">
                <key name="test1_test1">content1</key>
                <key name="test1_test2"/>
            </key>
            <key name="test2">content2</key>
            <key name="test3">content3</key>
            <key name="test4">content4</key>
        </key>
    </template-xml>
</template-request>
